### ISSUE TITLE
Option to change the "Change" (USD, EUR, GBP)

### ISSUE THREAD

**Issue by djste123** [luke-r-mills/CryptoNugget#15]
I'd like to change the Change using a new option in the menu, instead of hard coding it.

I was able to use the code on a st7789 1.3" 240x240 tft display with some modifications to your code.

Thank you!

**Comment by luke-r-mills** [comment]
Just pushed this functionality to the main branch.

Glad the code could be of use!

**Comment by luke-r-mills** [comment]
At the moment it wipes the existing candles when you switch currency, I might make it so that it just modifies the existing data in the candles rather than wipe them soon!
